library("quarto")
library("R.utils")
createLink(target=file.path("..", "_static"), link=".")
createLink(target=file.path("..", "astart", "down_java.qmd"), link=".")
createLink(target=file.path("..", "astart", "download_osm.qmd"), link=".")
createLink(target=file.path("..", "astart", "datarmor.qmd"), link=".")
createLink(target=file.path("..", "astart", "down_java.qmd"), link=".")
createLink(target=file.path("..", "astart", "running.qmd"), link=".")
createLink(target=file.path("..", "odd_des", "input.qmd"), link=".")
quarto_render()
