library("quarto")
library("R.utils")
createLink(target=file.path("..", "_static"), link=".")
createLink(target=file.path("..", "astart", "down_java.qmd"), link="1_download_requirements.qmd")
createLink(target=file.path("..", "astart", "download_osm.qmd"), link="2_install_osmose.qmd")
createLink(target=file.path("..", "astart", "datarmor.qmd"), link="3_datarmor_install.qmd")
createLink(target=file.path("..", "astart", "running.qmd"), link="4_running_osmose.qmd")
createLink(target=file.path("..", "odd_des", "input.qmd"), link="5_input.qmd")
quarto_render()
