# Introduction {.unnumbred}

The Osmose model assumes opportunistic predation based on spatial co-occurrence and size adequacy between a predator and its prey (size-based opportunistic predation). It represents fish individuals grouped in schools, which are characterised by their size, weight, age, taxonomy and geographic location (2D model). Each school is subject to different processes of the fish life cycle (growth, explicit predation, natural and starvation mortality, reproduction and migration) in addition to fishing mortality, which is different for each species and structured by age/size, space and season.

The model requires basic biological parameters for growth and reproduction processes, which are often available for a wide range of species, and which can be found, for example, in FishBase. It also needs to be forced by spatial distribution maps for each species, by age/size/stage and by season depending on data availability. Osmose provides a variety of size and species based ecological indicators can be produced and compared with in situ data (surveys and catch data) at different levels of aggregation: 

- at the species level (e.g. mean size, mean size-at-age, maximum size, mean trophic level, within-species distribution of TL)
- at the community level (e.g. slope and intercept of size spectrum, Shannon diversity index, mean TL of catch).

The model can be fitted to observed biomass and catch data, using a dedicated evolutionary algorithm. Recent developments have focused on the coupling of OSMOSE with various hydrodynamic and biogeochemical models, allowing for the construction of end-to-end models of marine ecosystems that explicitely account for the combined effects of climate and fishing on fish dynamics.
