#!/bin/csh
#PBS -q mpi_2
#PBS -l select=2:ncpus=28:mpiprocs=14:mem=125g
#PBS -l walltime=48:00:00

cd $PBS_O_WORKDIR

# activate osmose environment
source /usr/share/Modules/3.2.10/init/csh
setenv R_LIBS /home1/datawork/rioliver/libs/R/lib
module load R nco

setenv mpiproc `cat $PBS_NODEFILE | wc -l`

# Run R in parallel mode.
$MPI_LAUNCH /appli/R/3.6.3-intel-cc-17.0.2.174/lib64/R/library/snow/RMPISNOW \
--no-save -q < .calibration.R >>& calibration.out
