#!/bin/csh
#PBS -N osmose_calibration
#PBS -q sequentiel
#PBS -l mem=8g
#PBS -l walltime=00:25:00

source /usr/share/Modules/3.2.10/init/csh

# change to work directory
cd $PBS_O_WORKDIR




# export R_LIBS with the desired version of osmose and calibrar
setenv R_LIBS /home1/datawork/$USER/libs/R/lib

# Load modules (if available)
module load R
module load java
module load nco

# Load conda environment (if available)
#conda activate r4

# Run R script in sequential mode
time Rscript .calibration.R >>& mycalibration.log



