#!/bin/csh
#PBS -q omp
#PBS -l select=1:ncpus=56:mem=256g
#PBS -l walltime=240:00:00

cd $PBS_O_WORKDIR

# activate osmose environment
source /usr/share/Modules/3.2.10/init/csh
setenv R_LIBS /home1/datawork/rioliver/libs/R/lib
module load R/3.6.3-intel-cc-17.0.2.174
module load java/openjdk-16.0.2
module load nco

# run R in parallel mode
time Rscript .calibration.R --ncores=28 >>& mycalibration.log
