#!/bin/csh
#PBS -N osmose_calibration
#PBS -q omp
#PBS -l select=1:ncpus=56:mem=256g
#PBS -l walltime=240:00:00

source /usr/share/Modules/3.2.10/init/csh

# change to work directory
cd $PBS_O_WORKDIR




# export R_LIBS with the desired version of osmose and calibrar
setenv R_LIBS /home1/datawork/$USER/libs/R/lib

# Load modules (if available, choose versions working in parallel)
module load R/3.6.3-intel-cc-17.0.2.174
module load java/openjdk-16.0.2
module load nco

# Load conda environment (if available)
#conda activate r4

# Run R script in parallel mode
time Rscript .calibration.R --ncores=56 --omp --nht >>& mycalibration.log

