# Datarmor install

This section describes the easiest way to install Osmose on the Datarmor HPC. When running a job on Datarmor, you do not have access to the Internet. Therefore, the Java executables cannot be downloaded as discussed in @sec-java-executable. As a consequence, both the Java core and the R package must be compiled manually following @sec-install-sources.

In the following, we describe the steps to achieve this install on Datarmor.

## Loading the modules

From the Terminal, first load the necessary modules:

```bash
module load R/3.6.3-intel-cc-17.0.2.174
module load java/openjdk-16.0.2
module load nco
```

:::{.callout-important}
To use parallel R features, this specific R module is required
:::

:::{.callout-note}
The ``nco`` module is needed to have access to the NetCDF library
:::

## Set-up environment variables

Edit the ``~/.Renviron`` file and define the ``R_LIBS_USER`` environment variables as follows:

```bash
R_LIBS_USER=/home1/datawork/nbarrier/libs/R/lib
```

It specifies the location where the R libraries will be insalled.

:::{.callout-note}
The definition of the `OSMOSE_DIR` variable is not required since the Java sources will be generated by the compilation process.
:::

## Setting up conda

To have access to Git and Maven, the first step is to enable the use of Conda, through which these tools are available.

First, create a `~/.condarc` file, which contains the following lines:

```bash
envs_dirs:
  - ${DATAWORK}/anaconda3-envs
  - /home1/datahome/nbarrier/softwares/anaconda3-envs
  - /appli/conda-env
  - /appli/conda-env/2.7
  - /appli/conda-env/3.6
channels:
  - conda-forge
  - defaults
```

When this is done, if using CSH, type:

```csh
source /appli/anaconda/latest/etc/profile.d/conda.csh
```

If using BASH, type:

```bash
. /appli/anaconda/latest/etc/profile.d/conda.sh
```

:::{.callout-tip}
To make Conda permanently available, you can add the line above commands to your `~/.cshrc` or `~/.bashrc` files.
file
:::

## Cloning the code

Once Conda is set up, activate the Git environment by typing:

```
conda activate git
```

This will give you access to a ``git`` executable configured with the LFS support.

Finally, type the following:

```
git clone https://github.com/osmose-model/osmose.git
```

## Compiling the code {#sec-java-compile-datarmor}

To compile the Osmose Java code on Datarmor, you will need to use the ``maven`` conda environment. To activate it:

```
conda activate maven
```

Then, go in the ``osmose`` folder and type:

```
mvn package
```

The Java executable file is created in the ``inst/java/`` folder of the ``osmose`` directory.

## Installing the package

Once the Java code is compiled, you can install the Osmose R package.

First, install the required libraries as described in @sec-install-libraries.

Then, install the Osmose R package from the ``osmose`` folder:

```R
R CMD INSTALL .
```