
# Entities, state variables, and scales {#sec-state-variables}

## Entities

In the current section, the different types of entities of the Osmose model are described.

- The `Configuration` entity describes the parameters and entities that will be shared among the different simulations.
- The `Simulation` entity describes a given simulation. Simulations differ from each other if stochasticity is enabled.
- The `Cell` entity describes the individual cells of the Osmose computation 2D grid (longitude, latitude,
  cell index, etc.)
- The `Species` entity represents the species whose life-cycle is fully represented.
  This entity contain **fixed** parameters, which are not modified during the simulation.
- The `BackgroundSpecies` entity represents the species whose life-cycle is not represented. These species can feed on and be eaten by `Species`, and can be fished.
  This entity contain **fixed** parameters, which are not modified during the simulation.
- The `ResourceSpecies` entity represents the low-trophic level species. These species cannot predatate `Species` or `BackgroundSpecies` but can be eaten by them.
  This entity contain **fixed** parameters, which are not modified during the simulation.
- The `School` entity describes a group of `Species` individuals, whose life cycle is fully considered and which all share the
  same characteristics (age, weight, species, location, etc, trophic level).
- The `BackgroundSchool` entity describes a group of `BackgroundSpecies` individuals, whose biomass is provided as input and whose life-cycle is not simulated and which all share the
  same characteristics (age, weight, species, location, etc, trophic level).
- The `Resource` entity describes a swarm of `ResourceSpecies`, whose biomass is provided as input.

## State variables

### Simulation

The `Simulation` entity contains the following state variables:

{{< include _static/simu.qmd >}}

### Cell

The `Cell` entity contains the following state variables:

### Species

The `Species` entities contain the following state variables:

{{< include _static/species.qmd >}}

The `BackgroundSpecies` entities contain the following state variables:

{{< include _static/bkgspecies.qmd >}}

{{< include _static/rscspecies.qmd >}}

### School

The `School` entity contains the following state variables:

{{< include _static/school.qmd >}}

{{< include _static/bkgschool.qmd >}}

## Scales

The basic units of OSMOSE are fish schools, which are composed of individuals that belong to the same species, and that have the same age, size (length, weight), food requirements and, at a given time step, the same geographical coordinates. From the school states (hereafter called individual states), biomass and abundance can be tracked at the population or community levels along with the size, age, and spatial dimensions.

Other variables can be reported such as the trophic level, the diets, the different sources of mortality, the catches from fishing operations. Because each school simulated in OSMOSE is represented from the egg stage to the terminal age, which necessitates high calculation and memory capacities, and because comprehensive information on entire life cycles needs to be parameterized, the selection of focus species is made parsimoniously, and usually between 10 and 20 high-trophic level species or functional groups are explicitly considered in OSMOSE applications.

The model operates on a weekly to monthly time step, and runs up to 100 years or more depending on applications and simulations.

For eggs (age 0), weight and sizes are provided as parameters. For the others, conversion from size to weight (and conversely) is obtained by using allometric relationships:

$$
W = c \times L^b
$$

$$
L = \left(\frac{W}{c}\right)^{\frac{1}{3}}
$$

where the $c$ parameter is a condition factor, and $b$ the allometric power.

Biomass to abundance conversion for a school is made by using the mean weight of the school:

$$
B = N \times W
$$

$$
N = \frac{B}{W}
$$

{{< include _static/allometric.qmd >}}
