# Submodels

The genetic sub-model introduces a source of
intra-specific variability of quantitative traits in OSMOSE, through additive genetic variance $\sigma^2_{A,Z}$ and
expression variance $\sigma^2_{e,Z}$ and parental gene inheritance. The individuals are considered diploid
hermaphrodites, i.e. without differentiation between males and females, the model being based on female life
history. The genotypic values of the four heritable traits—maximum
mass-specific ingestion rate $I_{max}$, gonado-somatic index $r$ , intercept  and slope  of linear maturation reaction ($m_0$ and $m_1$, respectively)
norm—result from the expression of the corresponding functional loci. Neutral loci have no effect on
individuals’ phenotype: their evolution is the result of random drift.
Hereafter, the genetic sub-model is described for any of the four evolving traits, generically denoted $Z$.

```{toctree}
:caption: 'Contents:'
:maxdepth: 1

submodel/genetic_structure
submodel/trait_determinism
submodel/genetic_inheritance
```
