@startuml
class Species {
  name
  index
  fileIndex
  ..
  lifespan
  c
  bPower
  sizeMaturity
  ageMaturity
  eggSize
  eggWeight
  firstFeedingAgeDt
  larvaeToAdultsAgeDt
  {static} TL_EGG = 3f
}
@enduml