# This is a basic workflow to help you get started with Actions

name: R test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: R install
        uses: r-lib/actions/setup-r@master

      - name: Create R libs directories
        run: mkdir -p ~/R_osmose

      - name: Cache R dependencies
        id: r-dep
        uses: actions/cache@v2
        env:
            cache-name: r-dep-modules
        with:
            path: ~/R_osmose/R/lib
            key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/DESCRIPTION') }}

      - name: Install Osmose dependencies
        if: steps.r-dep.outputs.cache-hit != 'true'
        run: |
            install.packages(c("rlist", "knitr", "rmarkdown",
                               "stringr", "ncdf4","mgcv",
                               "fields"), repos="http://cran.us.r-project.org", lib="~/R_osmose")
        shell: Rscript {0}

      - name: Build Osmose without vignettes
        run: R CMD build --no-build-vignettes .
      
      - name: Test R directory
        run: ls ~/R_osmose/**/DESCRIPTION


